# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d51a382eb047eb89950d60e1ddffdadd725383c6a0df6e76e6227e25056106b89ac312476866790a53d3c505c819b399a7b5bf25b93087d30608f742f45e37fa

test:
  secret_key_base: ca95d9d48f42af62f512c74110145664442c6d47af8cddc9649f78444e69ba55051824897dacc9b977c96cf91b4b1b0bfe1bc11942db1c86cf988f91f50e55ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
